# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [93]:
import numpy as np
a = np.array([1,2,3,4])
print(np.all(a !=0))

True


In [94]:
# ejercicio 2
a = np.array([0,0,2,0])
print("el elemento no es cero:",np.any(a !=0))

el elemento no es cero: True


In [95]:
# ejercicio ..3
a = np.array([1,2, np.nan, np.inf])
print("tienen nan o inf:", np.isnan(a) | np.isinf(a))

tienen nan o inf: [False False  True  True]


In [96]:
# ejercicio 4
a = np.array([1,2, np.inf])
print("es infinito?", np.isinf(a))

es infinito? [False False  True]


In [97]:
#ejercicio 5
a = np.array([1, np.nan, 3])
print("sera NAN?", np.isnan(a))

sera NAN? [False  True False]


In [98]:
#ejericico 6
a = np.array([1, 3, 5])
z = np.array([2, 3, 4])
#creamos las impresiones con operadores logicos....
print(a > z)
print(z < a)
print(a >= z)
print(z <= a)
print(z == a)
print(a != z)
print(a % z) #un ppoco mas =)
print("un poco de mas", a + z)

[False False  True]
[False False  True]
[False  True  True]
[False  True  True]
[False  True False]
[ True False  True]
[1 0 1]
un poco de mas [3 6 9]


In [99]:
#ejercicio 7
#cual es la cantidad de memoria que ocupa el areglo =)
print("cantidad de memoria")
a = np.array([1, 7, 13, 105])
print(f"memoria que se ocupa:{a.nbytes}")

cantidad de memoria
memoria que se ocupa:32


In [100]:
#ejercicio 8
print("vanos a crear areglos =)")

print("a = es  igual al areglo de diez ceros =) ",np.zeros(10))
print("b = es igual al areglo de diez unos =) ", np.ones(10))
print("c = es igual al areglo de diez cincos *_* ", np.ones(10) *5)


vanos a crear areglos =)
a = es  igual al areglo de diez ceros =)  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
b = es igual al areglo de diez unos =)  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
c = es igual al areglo de diez cincos *_*  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [101]:
#ejercicio 9
print("quiero un rango de numeros del 30 al 70 +1 =) veremos: ", np.arange(30, 70 +1))
print("posdata: el numero mas 1 fue suficiente para que me diera hasta el 70 =)")

quiero un rango de numeros del 30 al 70 +1 =) veremos:  [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
posdata: el numero mas 1 fue suficiente para que me diera hasta el 70 =)


In [102]:
#ejericico numero 10: 
print("ejercicio numero 10 carnales: y quiere puros numero pares entre el 30 y 70 *-* ")

print("quieren numeros pares:", np.arange(30, 71, 2))
print("\n")
 

ejercicio numero 10 carnales: y quiere puros numero pares entre el 30 y 70 *-* 
quieren numeros pares: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]




In [103]:
#ejercicio 11
print("crear una matriz de 3 x 3 = 9")
print("tres filas x tres columnas ....")
print("esto es una matriz de identidad =) \n", np.eye(3))

crear una matriz de 3 x 3 = 9
tres filas x tres columnas ....
esto es una matriz de identidad =) 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [104]:
#ejercicio 12
numero = np.random.rand()
print(numero)

0.011493011836686717


In [105]:
#ejercicio numero 13
print(np.random.rand(15))

[0.4981157  0.22412529 0.15411607 0.00851962 0.24826117 0.8212135
 0.48527219 0.73077186 0.78633991 0.3799368  0.82615756 0.0842269
 0.69084204 0.70994464 0.78185499]


In [106]:
#ejercicio 14 
v = np.arange(15, 56)
print(v[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [107]:
#ejercicio 15
print(np.linspace(5, 50, 10))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [108]:
#ejercicio 16


In [109]:
#ejercicio 17
print("vamos a convertir a una lista de python")
a = np.array([1,2,3])
list_python = a.tolist()
print("asi quedo: ",list_python)

vamos a convertir a una lista de python
asi quedo:  [1, 2, 3]


In [110]:
#ejericicio 18:
L = [1,2,3]
areglo = np.array(L)
print(type(areglo))

<class 'numpy.ndarray'>


In [111]:
#ejercicio 19:  nuneros pares y acomodar en otra lista 
a = np.array([[1,2],[3,4]])
numeros_pares = a[a%2 == 0] #aqui dividimos entre dos el residuo...
print("aqui te mostrare los numeros pares",numeros_pares)


aqui te mostrare los numeros pares [2 4]


In [112]:
#ejercicio final
print("listo terminado: =)")
print("no usare m usare e = ")

e = np.array([[1,2,3], [4,5,6]])
#filas y columnas:
filas, columnas= e.shape
print(f"esta matriz tiene:{filas}: filas + {columnas} :columnas")


listo terminado: =)
no usare m usare e = 
esta matriz tiene:2: filas + 3 :columnas
